### ISSUE TITLE
PUT Update a key does not support removing Apis

### ISSUE THREAD

**Issue by aberthier** [apiaxle/apiaxle#75] opened 2015-06-03 03:11 UTC
The forApis parameters only supports adding new Apis, it does not remove Apis e.g. :
if I do a PUT with this array:
```javascript
{
  forApis: [1,2,3]
}
```

and then a PUT with this array
```javascript
{
  forApis: [1,3]
}
```

the API 2 will still be linked to the key

**Comment by fillup** [comment] 2016-10-04 20:49
This is caused by some limitations in the data format stored in redis. Since the API already exists for `/v1/api/:api/unlinkkey/:key` we're closing this issue. If you really still want this please reopen this issue and let us know.

**Closed by fillup** 2016-10-04 20:49 UTC
